### ISSUE TITLE
Adding wing configuration file

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#1792]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Following my talk to @hasanaburayyan regarding the SDK plugins, 
I thought it can be nice to add a config file (similar to .eslintrc, jest.config, or .tsconfig) in which the user can specify which plugins they want to use, and possibly some arguments for the plugins.
later on, we can add more customizable properties to the file.

### Use Cases

- It will ease the use of the plugins, and be a convenient way to share them across projects and repositories.
- Users could potentially run different plugins for different targets, and passing arguments to those functions may more convenient. 

### Component

SDK, Plugins

**Comment by hasanaburayyan** [comment]
Our plugin system is gonna be the coolest 💪 🚀

**Comment by Chriscbr** [comment]
I think it would be cool to have a dedicated configuration file to replace package.json. Using package.json sends the message that Wing isn't its own language. But to get rid of package.json fully, I think we'd need `wing` to install and manage dependencies for you.

```toml
# wing.toml
name = "my-project"
version = "0.1.0"
description = "My wing project!"
repository = { type = "github", user = "example", repo = "my-project" }
js-runtime = "deno" # default: "node"
platform = "aws" # the default platform to use when compiling

[dependencies]
"@cdktf/provider-aws" = "*"

[env]
FOO = "BAR"

[platforms]
aws = [ "tf-aws", "platform.static-backend.js" ] # define your own platforms
```
