### ISSUE TITLE
Paths are inconsistent

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#6108]
### I tried this:

my file tree is:
```
tf-generator:
    backend:
          - main.w
    public:
         (many website files)
````
I am trying to compile this code:
```
let website = new vite.Vite(
  root: "../public",
);
```

### This happened:

it works from within `tf-generator/backend`
with `wing compile main.w`

but doesn't from within `tf-generator`
with `wing compile backend/main.w`

### I expected this:

to take the path relative to the main file/ to the file it's written at

### Is there a workaround?

changing the path and be consistent of the compilation source

### Wing Version

0.66.5

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
