### ISSUE TITLE
Customize project-wide compile flags in `wing.toml`

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6776]
### Use Case

As a user I'd like to be able to be able to specify compile options in `wing.toml` in some way so that I don't have to type them or copy them every time I compile in my project.

Open questions:
- What kinds of compile options need to be overridden? Is the only use case to add platform extensions, or are there other options?

### Option 1

Allow defining custom target(s) in `wing.toml`, and then use that target with any overrides you've specified.

```toml
# wing.toml

[platforms.aws]
rootId = "myapp"
base_platform = "tf-aws"
platform_extensions = ["./s3-state.platform.js"]
```

Now, `wing compile -t aws` is a custom platform which extends `tf-aws` (a built-in platform) and applies the overrides  described by `s3-state.platform.js` on top.

### Option 2

Allow adding arbitrary compile flags for one or more targets/platforms that are always applied/added whenever you run `wing compile -t TARGET`.

For example:

```toml
# wing.toml

[platforms.tf-aws]
compile_flags = ["--platform", "~/.s3-state.platform.js", "--rootId", "myapp"]
```

Then `wing compile -t tf-aws` will automatically get run as `wing compile -t tf-aws --platform ~/.s3-state.platform.js`.

### Implementation Notes

Related:

- https://github.com/winglang/wing/issues/6466

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).
